TASK-3: MATRIX OPERATIONS TOOL (NUMPY)


In [8]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


In [7]:
print("\nAddition of A and B:")
print(A + B)


Addition of A and B:
[[ 6  8]
 [10 12]]


In [5]:
print("\nSubtraction of A and B:")
print(A - B)


Subtraction of A and B:
[[-4 -4]
 [-4 -4]]


In [6]:
print("\nTranspose of A and B:")
print(A - B)



Transpose of A and B:
[[-4 -4]
 [-4 -4]]


In [4]:
print("\nMultiplication of A and B:")
print(np.dot(A, B))


Multiplication of A and B:
[[19 22]
 [43 50]]


In [3]:
print("\nDeterminant of Matrix A:")
print(np.linalg.det(A))


Determinant of Matrix A:
-2.0000000000000004


In [2]:
print("\n--- Matrix Operations Tool ---")
print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Transpose")
print("5. Determinant")

choice = input("Enter your choice (1-5): ")

if choice == "1":
    print(A + B)
elif choice == "2":
    print(A - B)
elif choice == "3":
    print(np.dot(A, B))
elif choice == "4":
    print(A.T)
elif choice == "5":
    print(np.linalg.det(A))
else:
    print("Invalid choice")



--- Matrix Operations Tool ---
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
[[-4 -4]
 [-4 -4]]


In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\n--- Matrix Operations Tool ---")
print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Transpose")
print("5. Determinant")

choice = input("Enter your choice (1-5): ")

if choice == "1":
    print("\nAddition:")
    print(A + B)
elif choice == "2":
    print("\nSubtraction:")
    print(A - B)
elif choice == "3":
    print("\nMultiplication:")
    print(np.dot(A, B))
elif choice == "4":
    print("\nTranspose of A:")
    print(A.T)
elif choice == "5":
    print("\nDeterminant of A:")
    print(np.linalg.det(A))
else:
    print("Invalid choice")


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

--- Matrix Operations Tool ---
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
Invalid choice
